title: Rapunzel
author: Pritesh Rai
email: raijai127@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hope You are doing well see you soon in real world!

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
